In [1]:
#importing needed library
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
#Creating dataset
data = {'Temperature': ['Very Hot','Hot', 'Cold', 'Very Hot', 'Warm', 'Hot', 'Warm', 'Hot', 'Cold']}
df = pd.DataFrame(data, columns = ['Temperature'])
df

  Temperature
0    Very Hot
1         Hot
2        Cold
3    Very Hot
4        Warm
5         Hot
6        Warm
7         Hot
8        Cold

In [3]:
# One hot Encoding
ohc = OneHotEncoder()
df_new = pd.DataFrame(ohc.fit_transform(df[['Temperature']].values.reshape(-1,1)).toarray())
df_ohc = pd.concat([df, df_new], axis=1)
df_ohc

  Temperature    0    1    2    3
0    Very Hot  0.0  0.0  1.0  0.0
1         Hot  0.0  1.0  0.0  0.0
2        Cold  1.0  0.0  0.0  0.0
3    Very Hot  0.0  0.0  1.0  0.0
4        Warm  0.0  0.0  0.0  1.0
5         Hot  0.0  1.0  0.0  0.0
6        Warm  0.0  0.0  0.0  1.0
7         Hot  0.0  1.0  0.0  0.0
8        Cold  1.0  0.0  0.0  0.0

In [4]:
#Dummy Encoding 
df_dummy = pd.get_dummies(df, prefix = ['Temp'], columns = ['Temperature'])
df_dummy = pd.concat([df, df_dummy], axis=1)
df_dummy

  Temperature  Temp_Cold  Temp_Hot  Temp_Very Hot  Temp_Warm
0    Very Hot          0         0              1          0
1         Hot          0         1              0          0
2        Cold          1         0              0          0
3    Very Hot          0         0              1          0
4        Warm          0         0              0          1
5         Hot          0         1              0          0
6        Warm          0         0              0          1
7         Hot          0         1              0          0
8        Cold          1         0              0          0

In [5]:
df_dummy_t = pd.get_dummies(df, prefix = ['Temp'], columns = ['Temperature'], drop_first=True)
df_dummy_t = pd.concat([df, df_dummy_t], axis=1)
df_dummy_t

  Temperature  Temp_Hot  Temp_Very Hot  Temp_Warm
0    Very Hot         0              1          0
1         Hot         1              0          0
2        Cold         0              0          0
3    Very Hot         0              1          0
4        Warm         0              0          1
5         Hot         1              0          0
6        Warm         0              0          1
7         Hot         1              0          0
8        Cold         0              0          0